<?php

namespace Modules\Dummy\Database\Seeders\Modules\Coupon;

use Illuminate\Database\Seeder;

class CouponsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('coupons')->delete();

        \DB::table('coupons')->insert([
            0 => [
                'id' => 2,
                'name' => 'Coupon1',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 5,
                'minimum_spend' => '3000.00000000',
                'usage_count' => null,
                'code' => 'xyz012',
                'discount_type' => 'Percentage',
                'discount_amount' => '30.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            1 => [
                'id' => 3,
                'name' => 'Eid Special',
                'vendor_id' => null,
                'shop_id' => null,
                'usage_limit' => 5,
                'minimum_spend' => null,
                'usage_count' => null,
                'code' => 'EID012',
                'discount_type' => 'Flat',
                'discount_amount' => '500.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            2 => [
                'id' => 4,
                'name' => 'Eid coupon',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 7,
                'minimum_spend' => '3000.00000000',
                'usage_count' => null,
                'code' => 'ramadan55',
                'discount_type' => 'Percentage',
                'discount_amount' => '30.00000000',
                'maximum_discount_amount' => '1500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            3 => [
                'id' => 5,
                'name' => 'coupon2',
                'vendor_id' => null,
                'shop_id' => null,
                'usage_limit' => 2,
                'minimum_spend' => '5000.00000000',
                'usage_count' => null,
                'code' => 'xyz-12',
                'discount_type' => 'Percentage',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => '3000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            4 => [
                'id' => 6,
                'name' => 'coupon3',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '3000.00000000',
                'usage_count' => null,
                'code' => 'code123',
                'discount_type' => 'Percentage',
                'discount_amount' => '99.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            5 => [
                'id' => 7,
                'name' => 'coupon6',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => null,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'code--012',
                'discount_type' => 'Flat',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            6 => [
                'id' => 8,
                'name' => 'coupon4',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '5000.00000000',
                'usage_count' => null,
                'code' => 'codexyz',
                'discount_type' => 'Percentage',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            7 => [
                'id' => 9,
                'name' => 'coupon5',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 4,
                'minimum_spend' => '5000.00000000',
                'usage_count' => null,
                'code' => 'code40',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            8 => [
                'id' => 10,
                'name' => 'coupon7',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 2,
                'minimum_spend' => '10000.00000000',
                'usage_count' => null,
                'code' => 'code50',
                'discount_type' => 'Percentage',
                'discount_amount' => '80.00000000',
                'maximum_discount_amount' => '5000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            9 => [
                'id' => 11,
                'name' => 'coupon8',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 3,
                'minimum_spend' => null,
                'usage_count' => null,
                'code' => 'promo2022',
                'discount_type' => 'Flat',
                'discount_amount' => '70.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            10 => [
                'id' => 12,
                'name' => 'coupon9',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 10,
                'minimum_spend' => '10000.00000000',
                'usage_count' => null,
                'code' => 'coupon100',
                'discount_type' => 'Percentage',
                'discount_amount' => '60.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            11 => [
                'id' => 13,
                'name' => 'coupon10',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 10,
                'minimum_spend' => null,
                'usage_count' => null,
                'code' => 'Flat50',
                'discount_type' => 'Flat',
                'discount_amount' => '50.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            12 => [
                'id' => 14,
                'name' => 'coupon11',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => null,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'couponcode',
                'discount_type' => 'Percentage',
                'discount_amount' => '40.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            13 => [
                'id' => 15,
                'name' => 'coupon13',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 8,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'code0000',
                'discount_type' => 'Percentage',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => '1000.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            14 => [
                'id' => 16,
                'name' => 'coupon15',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => null,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'coupon15',
                'discount_type' => 'Flat',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            15 => [
                'id' => 17,
                'name' => 'coupon16',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => null,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'code60',
                'discount_type' => 'Percentage',
                'discount_amount' => '20.00000000',
                'maximum_discount_amount' => '500.00000000',
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            16 => [
                'id' => 18,
                'name' => 'Eid',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '200.00000000',
                'usage_count' => null,
                'code' => 'MOONeid',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            17 => [
                'id' => 19,
                'name' => 'Clark Dominguez',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'mkknkdMMr',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            18 => [
                'id' => 20,
                'name' => 'Clark Doominguez',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'MOOoNeid',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
            19 => [
                'id' => 21,
                'name' => 'Picked Up',
                'vendor_id' => 1,
                'shop_id' => null,
                'usage_limit' => 1,
                'minimum_spend' => '1000.00000000',
                'usage_count' => null,
                'code' => 'mkknkdMMr9',
                'discount_type' => 'Flat',
                'discount_amount' => '100.00000000',
                'maximum_discount_amount' => null,
                'start_date' => randomDateBefore(30),
                'end_date' => randomDateAfter(30),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => null,
            ],
        ]);
    }
}
