<?php

namespace Modules\Dummy\Database\Seeders\Modules\Shipping;

use Illuminate\Database\Seeder;

class ShippingZoneShippingMethodsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('shipping_zone_shipping_methods')->delete();

        \DB::table('shipping_zone_shipping_methods')->insert([
            0 => [
                'id' => 172,
                'shipping_zone_id' => 1,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'class',
                'requirements' => null,
                'status' => 1,
            ],
            1 => [
                'id' => 173,
                'shipping_zone_id' => 1,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '0.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            2 => [
                'id' => 174,
                'shipping_zone_id' => 1,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            3 => [
                'id' => 175,
                'shipping_zone_id' => 2,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'order',
                'requirements' => null,
                'status' => 1,
            ],
            4 => [
                'id' => 176,
                'shipping_zone_id' => 2,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '2.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            5 => [
                'id' => 177,
                'shipping_zone_id' => 2,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            6 => [
                'id' => 178,
                'shipping_zone_id' => 3,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '0.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'order',
                'requirements' => null,
                'status' => 1,
            ],
            7 => [
                'id' => 179,
                'shipping_zone_id' => 3,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '0.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            8 => [
                'id' => 180,
                'shipping_zone_id' => 3,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            9 => [
                'id' => 181,
                'shipping_zone_id' => 4,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '3.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'class',
                'requirements' => null,
                'status' => 1,
            ],
            10 => [
                'id' => 182,
                'shipping_zone_id' => 4,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '0.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            11 => [
                'id' => 183,
                'shipping_zone_id' => 4,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            12 => [
                'id' => 184,
                'shipping_zone_id' => 5,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '2.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'class',
                'requirements' => null,
                'status' => 1,
            ],
            13 => [
                'id' => 185,
                'shipping_zone_id' => 5,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            14 => [
                'id' => 186,
                'shipping_zone_id' => 5,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            15 => [
                'id' => 187,
                'shipping_zone_id' => 6,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '2.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'order',
                'requirements' => null,
                'status' => 1,
            ],
            16 => [
                'id' => 188,
                'shipping_zone_id' => 6,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            17 => [
                'id' => 189,
                'shipping_zone_id' => 6,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            18 => [
                'id' => 190,
                'shipping_zone_id' => 7,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'class',
                'requirements' => null,
                'status' => 1,
            ],
            19 => [
                'id' => 191,
                'shipping_zone_id' => 7,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            20 => [
                'id' => 192,
                'shipping_zone_id' => 7,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 1,
            ],
            21 => [
                'id' => 193,
                'shipping_zone_id' => 8,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '2.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'class',
                'requirements' => null,
                'status' => 1,
            ],
            22 => [
                'id' => 194,
                'shipping_zone_id' => 8,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            23 => [
                'id' => 195,
                'shipping_zone_id' => 8,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
            24 => [
                'id' => 196,
                'shipping_zone_id' => 9,
                'shipping_method_id' => 3,
                'method_title' => 'Flat Rate',
                'tax_status' => 'taxable',
                'cost' => '10.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => 'order',
                'requirements' => null,
                'status' => 1,
            ],
            25 => [
                'id' => 197,
                'shipping_zone_id' => 9,
                'shipping_method_id' => 2,
                'method_title' => 'Local Pickup',
                'tax_status' => 'none',
                'cost' => '1.00000000',
                'cost_type' => 'cost_per_order',
                'calculation_type' => null,
                'requirements' => null,
                'status' => 1,
            ],
            26 => [
                'id' => 198,
                'shipping_zone_id' => 9,
                'shipping_method_id' => 1,
                'method_title' => 'Free Shipping',
                'tax_status' => null,
                'cost' => '0.00000000',
                'cost_type' => null,
                'calculation_type' => '0',
                'requirements' => '',
                'status' => 0,
            ],
        ]);

    }
}
